### ISSUE TITLE
Change expiration time to constant

### ISSUE THREAD

**Issue by greyfiles** [greyfiles/expertiza#8]
Line 41: URL expires after 1 day. This time should not be hardwired; it should be a constant or a parameter. Replace 1 day with some constant that contains 1 as value.

**Comment by colin-odowd** [comment]
Closed with commit 3f0b51f6f2f106df8338483396a95d4068e39c7f

**Comment by colin-odowd** [comment]
Closed with commit 3f0b51f6f2f106df8338483396a95d4068e39c7f
